---
apiVersion: v1
kind: Service
metadata:
  name: my-nodejs
  labels:
    run: my-nodejs
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
  selector:
    run: my-nodejs
